[tool.cibuildwheel]
# Build using the latest manylinux2014 release, instead of the cibuildwheel
# pinned version
manylinux-x86_64-image = 'manylinux_2_28'
manylinux-aarch64-image = 'manylinux_2_28'

# Switch to using build
build-frontend = "build"

# Disable repairing wheel / Compiled binary incompatible in python <3.7
#repair-wheel-command = []

# Only build on CPython 3.7
build = "cp37-*"

# Tests
test-command = "python -m unittest discover -s {project}/tests"

# Build `universal2` and `arm64` wheels on an Intel runner.
# Note that the `arm64` wheel and the `arm64` part of the `universal2`
# wheel cannot be tested in this configuration.
[tool.cibuildwheel.macos]
archs = ["x86_64", "universal2", "arm64"]

# On an Linux Intel runner with qemu installed, build Intel and ARM wheels
[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
before-all = ["yum install gtk3 -y"]

[tool.cibuildwheel.windows]
archs = ["AMD64", "x86", "ARM64"]
